"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Country_1 = require("./Country");
var countryManager_1 = require("./countryManager");
var countryManager = new countryManager_1.CountryManager();
var VietNam = new Country_1.seagame(10, 7, 8, "VietNam");
var Lao = new Country_1.seagame(4, 5, 7, "Lao");
var ThaiLan = new Country_1.seagame(6, 5, 3, "ThaiLan");
var Campuchia = new Country_1.seagame(2, 4, 8, "Campuchia");
var Indo = new Country_1.seagame(1, 3, 8, "Indo");
var Viet = new Country_1.seagame(10, 7, 8, "Viet");
var Uiet2 = new Country_1.seagame(10, 7, 8, "Aiet");
countryManager.add(VietNam);
countryManager.add(Lao);
countryManager.add(ThaiLan);
countryManager.add(Campuchia);
countryManager.add(Indo);
countryManager.add(Viet);
countryManager.add(Uiet2);
console.log(countryManager.countrySort());
